[NAMBA1] beckend MainProductListView
wecode-bootcamp-korea/33-1st-Namba1-backend pull request #10
Opened 2022-05-30 12:19 UTC by nicholas019

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- main 페이지  MainProductListView API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인페이지 기능구현
 - 테마별 조회 기능
    : 담백한맛 , 새콤한맛, 매콤한맛, 짭짤한맛, 이국적인맛 총 5가지 테마별 반환
      이미지는 product 이미지들 중 세번째 이미지 사용
 - 신메뉴 조회 기능
   : 등록순(-id)으로 조회하여 그중 최근 6개만 반환 
     이미지는 product 이미지들 중 두번째 이미지 사용 
 - 모든 메뉴 조회 기능
   : 모든 메뉴 등록순으로 조회
     이미지는 product 이미지들 중 세번째 이미지 사용
 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- request의 요청이 하나의 API에 여러개의 요청을 받아 여러개의 response를 할 수 있다는것에 대한 이해

<br />

## :: 기타 질문 및 특이 사항
- user/views.py는 회원가입 API 프론트엔드 통신중에 수정하였으나 다시 원상복구 하였습니다.

2022-05-31 02:03 UTC, autoboy4commit commented
해당 PR은 라이브 코드리뷰 때 같이 보겠습니다 한구님!! 🙂

2022-05-31 09:46 UTC, lordmyshepherd requested changes

2022-05-31 09:46 UTC, lordmyshepherd commented on products/views.py
> +class MainProductListView(View):
ProductListView와 합쳐주세요.

```python
from django.http import JsonResponse
from django.views import View

from .models import Product, Theme

class ProductListView(View):
    # GET products -> all
    # GET products?themeId=1
    # GET products?themeId=1&sort="id"
    # GET products?themeId=1&sort="-id"
    # GET products?themeId=1&sort="-price"
    def get(self, request):
        """
        product table에 thumnail_image column 추가.
        """
        try:
            theme_id = request.GET.get('theme_id', None)
            search   = request.GET.get('search', None)
            sort     = request.GET.get('sort', "-id")
            is_new   = request.GET.get('is_new', False)

            filter_set = {}
            
            if theme_id:
                filter_set["producttheme__theme_id"] = theme_id

            if search:
                filter_set["name__contains"] = search

            if is_new: # product에 is_new column 추가.
                filter_set["is_new"] = is_new
            
            products = Product.objects.filter(**filter_set).order_by(sort)

            product_list = [{
                # 추가로 필요한 컬럼 추가.
                "id"             : product.id,
                "name"           : product.name,
                "serving"        : product.serving,
                "cookTime"       : product.cook_time,
                "thumnail_image" : product.thumnail_image,
                "price"          : int(product.price),
                "spice"          : [spice.level for spice in product.spice_set.all()],
                "image"          : [image.image for image in product.productimage_set.all()]
            } for product in products]

            return JsonResponse({'product_list': product_list}, status=200)

        except KeyError:
            return JsonResponse({"message": 'KeyError'}, status = 400)

```

2022-05-31 09:46 UTC, lordmyshepherd commented on products/views.py
> +class MainProductListView(View):
if문을 줄이는 방법 참고해주세요.

```python
            filter_set = {
                "theme_id" : "producttheme__theme_id",
                "search"   : "name__contains",
                "is_new"   : "is_new"
            }

            filter = {filter_set[key] : value for key, value in request.GET.items()}
           
            products = Product.objects.filter(**filter).order_by(sort)


```

2022-06-01 05:17 UTC, nicholas019 commented
라이브리뷰때 피드백주셨던부분 수정해서 올렸습니다

2022-06-01 07:25 UTC, Jon9Beom commented
LGTM 🚀

2022-06-01 07:26 UTC, merged