Feature/cart
wecode-bootcamp-korea/33-1st-Namba1-backend pull request #11
Opened 2022-05-31 07:00 UTC by nicholas019

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 기능 (CRUD) 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Create(POST Method)
 - 장바구니의 넣을 정보(product_id, quantity)는 body로 받고, user의 정보는 token을 통해 받아서 저장하는 기능
 
2. Read(GET Method)
 - Cart DB에 담긴 정보를 조회하는 기능
 - token을 이용해 얻은 uesr 정보를 이용해 cartDB를 조회해서 데이터를 받은뒤 그중에 cart에 필요한 정보만 반환해주는 기능.
 - 반환시 image의 경우 cartDB의 정보중 product_id를 이용해 product_imageDB를 조회하여 그중 3번째 사진을 인덱스하여 반환

3. Update(PATCH Method)
 - body에 담긴 요청(product_id, quantity)값을 받고 token값으로 user정보를 받은뒤 unique 제약이 걸려있는 product_id/user_id의 기능을 이용하여 get함수로 cart_id값을 가져와 그중 body에 담겨있던 quantity값으로 교체 해준뒤 저장하는 기능

4. Delete(DELETE Method)
 - query parameter로 받은 cart_id의 값을 받아 delete 함수를 이용해 레코드를 삭제하는 기능
 <br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-05-31 07:18 UTC, nicholas019 commented
Type Error 및 DoesNotExist 추가

2022-05-31 10:01 UTC, lordmyshepherd requested changes

2022-05-31 10:01 UTC, lordmyshepherd commented on orders/views.py
> +class CartView(View):
```python
class CartView(View):
    @login_required
    def post(self, request):
        try:
            data = json.loads(request.body)

            quantity   = data["quantity"]
            product_id = data["product_id"]
            user_id    = request.user.id
            
            cart, created = Cart.objects.get_or_create(
                product_id = product_id,
                user_id    = user_id,
                defaults = {"quantity" : quantity}
            )

            if not created:
                cart.quantity += quantity
                cart.save()

            return JsonResponse({'message':'SUCCES'}, status=200)

        except KeyError:
            return JsonResponse({"message": 'KEY_ERROR'}, status = 400)

        except Cart.DuplicateError:
            return JsonResponse({"message": '이미 장바구니에 담겨있습니다'}, status = 400)    

    @token_reader
    def get(self, request):
        try:
            carts = Cart.objects.filter(user_id = request.user)
            
            cart_list=[{
                "user_id"      : cart.user_id,
                "product_name" : cart.product.name,
                "product_price": int(cart.product.price),
                # thumbnail_image 수정
                "product_image": ProductImage.objects.filter(product_id=cart.product_id)[2].image,
                "quantity"     : cart.quantity,
            } for cart in carts]

            return JsonResponse({ "carts":cart_list}, status=200) 
        except KeyError:
            return JsonResponse({"message": 'KEY_ERROR'}, status = 400)    

    @token_reader
    #PATCH carts/1
    def patch(self, request, cart_id):
        try:
            cart_data = json.loads(request.body)

            quantity   = cart_data["quantity"]
            user_id    = request.user

            cart = Cart.objects.get(user_id = user_id, id = cart_id)

            cart.quantity = quantity
            cart.save()

            return JsonResponse({"message":"UPDATE SUCCESS"}, status=200)

        except KeyError:
            return JsonResponse({"message": 'KEY_ERROR'}, status = 400)
        except Cart.DoesNotExist:
            return JsonResponse({"message": 'Not found Data'}, status = 400)    

    def delete(self, request, cart_id):
        Cart.objects.filter(id = cart_delete, user_id = request.user.id).delete()

        return JsonResponse({"message":"DELETE SUCCESS"}, status=200) 
```

2022-06-01 14:46 UTC, nicholas019 commented
피드백 부분 수정 완료 하였습니다 감사합니다.

2022-06-02 01:46 UTC, bigfanoftim approved these changes
LGTM 👍

2022-06-02 01:46 UTC, merged