[Namba1팀]backend models
wecode-bootcamp-korea/33-1st-Namba1-backend pull request #2
Opened 2022-05-25 01:51 UTC by nicholas019

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- ERD를 바탕으로 models.py 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. app 총 5개 생성 (users, product, reviews, carts, orders)2. 
2. models.py 작성 중
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-25 04:02 UTC, nicholas019 commented
https://dbdiagram.io/d/628c6fc8f040f104c183a5c7

2022-05-25 04:11 UTC, nicholas019 commented
db_table 일부 수정안된체로 push하여 바로 수정하고 다시 push하였습니다

2022-05-25 05:38 UTC, autoboy4commit commented on orders/models.py
> +class OrderItime(models.Model):
```suggestion
class OrderItem(models.Model): 
```

2022-05-25 05:38 UTC, autoboy4commit commented on products/models.py
> +    product_image = models.CharField(max_length=100)
상품 이미지에 대한 데이터는 어떤걸로 저장하나요? 만약 보통의 경우와 같이 URL로 저장하신다면 max_length를 지금보다 더 넉넉히 지정해주는게 좋을 것 같습니다.
```suggestion
    product_image = models.CharField(max_length=300)
```

2022-05-25 05:38 UTC, autoboy4commit commented on products/models.py
> +        db_table = 'product_theme'
```suggestion
        db_table = 'product_themes'
```

2022-05-25 05:38 UTC, autoboy4commit commented on users/models.py
> +    address          = models.CharField(max_length=15)
Delivery 클래스의 `address`는 주소인가요 번지인가요? 보다 넉넉하게 설정할 필요가 있어보입니다.

2022-05-25 05:38 UTC, autoboy4commit commented on reviews/models.py
> +    review_image   = models.CharField(max_length=100)
마찬가지입니다~~!

2022-05-25 05:54 UTC, lordmyshepherd requested changes

2022-05-25 05:54 UTC, lordmyshepherd commented on orders/models.py
> +        db_table = 'carts'
user와 product에 unique together 제약 조건을 추가해야될 것 같습니다.
왜 필요한지는 코멘트로 남겨주세요~

2022-05-25 05:54 UTC, lordmyshepherd commented on products/models.py
> +    product_content = models.CharField(max_length=300)
Product class의 member 변수로 name, content가 선언되기 때문에 앞에 `product_`를 붙이지 않아도 될 것 같습니다!

```suggestion
    name    = models.CharField(max_length=15)
    content = models.CharField(max_length=300)
```

2022-05-25 05:54 UTC, lordmyshepherd commented on reviews/models.py
> +    review_image   = models.CharField(max_length=100)
위에서 드린 피드백과 동일합니다.
```suggestion
    title   = models.CharField(max_length=30)
    content = models.CharField(max_length=150)
    image   = models.CharField(max_length=100)
```

2022-05-25 05:54 UTC, lordmyshepherd commented on users/models.py
> +        db_table = 'users'
unique 제약 조건 필요할 것 같습니다!

2022-05-25 05:54 UTC, lordmyshepherd commented on users/models.py
> +    password     = models.CharField(max_length=100)
max_length 100으로 충분한가요?

2022-05-25 07:09 UTC, nicholas019 commented on users/models.py
> +    password     = models.CharField(max_length=100)
패스워드의경우 위스타그램 작업할때 bcrypt를 활용해서 암호화를 진행할때 100이하에서 충분히 가능하다고 생각되어 100으로 도 충분하다고 생각합니다. 당시에 혹시나해서 비밀번호를 길게해보거나 짧게해봐도 동일한 길이여서 100으로 결정했습니다

2022-05-25 07:11 UTC, nicholas019 commented on users/models.py
> +        db_table = 'users'
확인해서 email에 unique속성 부여했습니다

2022-05-25 07:16 UTC, nicholas019 commented on users/models.py
> +    address          = models.CharField(max_length=15)
네 수정했습니다

2022-05-25 08:17 UTC, nicholas019 commented on orders/models.py
> +class OrderItime(models.Model):
수정했습니다 !

2022-05-25 08:18 UTC, nicholas019 commented on products/models.py
> +    product_image = models.CharField(max_length=100)
네 300으로 수정했습니다

2022-05-25 08:18 UTC, nicholas019 commented on products/models.py
> +        db_table = 'product_theme'
테이블명 수정했습니다 감사합니다

2022-05-25 08:32 UTC, nicholas019 commented on orders/models.py
> +        db_table = 'carts'
제약조건을 하는 이유는 장바구니의경우 하나의 제품을 선택하고 같은 제품을 선택하면 추가로 레코드가 생기는 것이 아니라 기존에 있던것에서 quantity만 변경되는데 views.py에서 조건을 걸어 변경해줄 수도있지만 DB에 제약을 걸어 원천차단을 하기위해 제약을 거는 것 같습니다

2022-05-25 08:32 UTC, nicholas019 commented on reviews/models.py
> +    review_image   = models.CharField(max_length=100)
모두 변경했습니다

2022-05-25 08:58 UTC, autoboy4commit commented on users/models.py
> +        abstract = True
한구님~ TimeStampModel 만들어서 여러 클래스에 잘 상속하셨네요!
한가지 피드백 드리자면 현재 `TimeStampModel` 클래스는 여러 앱 (users, products, orders...)에서 사용되고 있습니다. 
이런 경우에는 일반적으로 `core`라는 별도의 앱을 만들어 `core/models.py` 에 작성하여 import 합니다.
(추가로 validation_check, login_decorator 같은 것들도 `core/utils.py`에서 작성, 관리합니다.)

2022-05-25 08:58 UTC, autoboy4commit commented on orders/models.py
> +        db_table = 'carts'
unique 설정과 이유에 대한 설명 감사합니다!

다만 django 공식문서에서는 `unique_together` 보다는 `UniqueConstraint`을 사용하도록 권장하고 있습니다!
수정해주세요~

![image](https://user-images.githubusercontent.com/94527515/170223652-bb6ad693-3eeb-4b0a-8b0e-a2cc2b158a30.png)

2022-05-25 09:05 UTC, nicholas019 commented on users/models.py
> +        abstract = True
네 바로 수정하겠습니다!

2022-05-25 10:52 UTC, nicholas019 commented on orders/models.py
> +        db_table = 'carts'
UniqueConstraint로 수정했습니다!

2022-05-26 01:00 UTC, autoboy4commit commented
LGTM 👍

2022-05-26 01:00 UTC, merged